version: '2'
vars:
    VERSION: 1.0.0
tasks:
    build:
        cmds:
            - go build -tags forceposix -a -v -ldflags "-s -w"
    all-releases:
        cmds:
            - echo "Building all releases"
            - echo "Building macOS release"
            - task: macos-release
            - echo "Building Linux release"
            - task: linux-release
            - echo "Building Windows release"
            - task: windows-release
            - echo "Build done"
    macos-release:
        cmds:
            - GOOS=darwin GOARCH=amd64 go build -tags forceposix -a -v -ldflags "-s -w" -o emtpostproc.macos
            - gtar cjvf emtpostproc-{{.VERSION}}-x86_64-apple-darwin.tar.bz2 --transform 'flags=r;s|emtpostproc.macos|emtpostproc|' --transform 'flags=r;s,^,emtpreproc-{{.VERSION}}/,'  templates emtpostproc.macos
    linux-release:
        cmds:
            - GOOS=linux GOARCH=amd64 go build -tags forceposix -a -v -ldflags "-s -w" -o emtpostproc.linux
            - gtar cjvf emtpostproc-{{.VERSION}}-i386-x86_64-pc-linux-gnu.tar.bz2 --transform 'flags=r;s|emtpostproc.linux|emtpostproc|' --transform 'flags=r;s,^,emtpreproc-{{.VERSION}}/,'  templates emtpostproc.linux
    windows-release:
        cmds:
            - GOOS=windows GOARCH=386 go build -tags forceposix -a -v -ldflags "-s -w" -o emtpostproc.windows
            - gtar cjvf emtpostproc-{{.VERSION}}-i686-mingw32.tar.bz2 --transform 'flags=r;s|emtpostproc.windows|emtpostproc|' --transform 'flags=r;s,^,emtpreproc-{{.VERSION}}/,'  templates emtpostproc.windows
    clean:
        cmds:
            - rm -f emtpostproc emtpostproc.windows emtpostproc.linux emtpostproc.macos emtpostproc-{{.VERSION}}*
    copy2s3:
        cmds:
            - s3cmd put --acl-public emtpostproc-{{.VERSION}}-x86_64-apple-darwin.tar.bz2 s3://energiaUS/tools/macosx/
            - s3cmd put --acl-public emtpostproc-{{.VERSION}}-i386-x86_64-pc-linux-gnu.tar.bz2 s3://energiaUS/tools/linux64/
            - s3cmd put --acl-public emtpostproc-{{.VERSION}}-i686-mingw32.tar.bz2 s3://energiaUS/tools/windows/
